In [1]:
import pandas as pd

data = pd.DataFrame({ 'gender' : ['Male', 'Female', 'Male', 'Female', 'Female'],
                       'class' : ['A','B','C','D','A'],
                        'city' : ['Delhi','Gurugram','Delhi','Delhi','Gurugram'] })
data.head()

   gender class      city
0    Male     A     Delhi
1  Female     B  Gurugram
2    Male     C     Delhi
3  Female     D     Delhi
4  Female     A  Gurugram

# Categorical data
Many different ways to handle categorical data and many different Python packages.

## category_encoders package
### Implementing one-hot encoding through category_encoder

In this method, each category is mapped to a vector that contains 1 and 0 denoting the presence or absence of the feature. The number of vectors depends on the number of categories for features.

In [14]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

one_hot_encoder.set_output(transform="pandas")
one_hot_encoded_df = one_hot_encoder.fit_transform(data["gender"].to_frame())

one_hot_encoded_df.head()

   gender_Female  gender_Male
0            0.0          1.0
1            1.0          0.0
2            0.0          1.0
3            1.0          0.0
4            1.0          0.0

### Binary Encoding
Binary encoding converts a category into binary digits. Each binary digit creates one feature column.


![alt text](images/binary_encoding.png)

In [15]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

one_hot_encoder.set_output(transform="pandas")
one_hot_encoded_df = one_hot_encoder.fit_transform(data["class"].to_frame())

one_hot_encoded_df.head()

   class_A  class_B  class_C  class_D
0      1.0      0.0      0.0      0.0
1      0.0      1.0      0.0      0.0
2      0.0      0.0      1.0      0.0
3      0.0      0.0      0.0      1.0
4      1.0      0.0      0.0      0.0

In [17]:
# Applying one-hot encoding to a column in a dataframe --> Bringing it together with Pandas manipulations
# Sample data
data = pd.DataFrame({
    'gender': ['Male', 'Female', 'Male', 'Female', 'Female'],
    'class': ['A', 'B', 'C', 'D', 'A'],
    'city': ['Delhi', 'Gurugram', 'Delhi', 'Delhi', 'Gurugram']
})

# Display the first few rows of the original dataframe
print("Original DataFrame:")
print(data.head())

# Instantiate OneHotEncoder with handle_unknown='ignore' and sparse_output=False
one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Set the output format to pandas dataframe
one_hot_encoder.set_output(transform="pandas")

# Apply one-hot encoding to the 'class' column
one_hot_encoded_df = one_hot_encoder.fit_transform(data[['class']])

# Display the one-hot encoded columns
print("\nOne-Hot Encoded 'class' Column:")
print(one_hot_encoded_df.head())

# Concatenate the one-hot encoded columns back to the original dataframe
data_with_one_hot = pd.concat([data.drop(['class'], axis=1), one_hot_encoded_df], axis=1)

# Display the dataframe after adding one-hot encoded columns
print("\nDataFrame After Adding One-Hot Encoded 'class' Column:")
print(data_with_one_hot.head())

Original DataFrame:
   gender class      city
0    Male     A     Delhi
1  Female     B  Gurugram
2    Male     C     Delhi
3  Female     D     Delhi
4  Female     A  Gurugram

One-Hot Encoded 'class' Column:
   class_A  class_B  class_C  class_D
0      1.0      0.0      0.0      0.0
1      0.0      1.0      0.0      0.0
2      0.0      0.0      1.0      0.0
3      0.0      0.0      0.0      1.0
4      1.0      0.0      0.0      0.0

DataFrame After Adding One-Hot Encoded 'class' Column:
   gender      city  class_A  class_B  class_C  class_D
0    Male     Delhi      1.0      0.0      0.0      0.0
1  Female  Gurugram      0.0      1.0      0.0      0.0
2    Male     Delhi      0.0      0.0      1.0      0.0
3  Female     Delhi      0.0      0.0      0.0      1.0
4  Female  Gurugram      1.0      0.0      0.0      0.0

## Which encoding is best?
![alt text](images/best_encoding.png)

*source: https://www.kdnuggets.com/2021/05/deal-with-categorical-data-machine-learning.html*

## Encoding exercises

In [ ]:
import pandas as pd

# Larger Sample Data related to housing prices
sample_data_from_houses = pd.DataFrame({
    'date_sold': ['2023-01-01', '2023-02-15', '2023-03-10', '2023-04-25', '2023-05-30',
                  '2023-06-10', '2023-07-15', '2023-08-20', '2023-09-25', '2023-10-30'],
    'price': [250000, 300000, 150000, 500000, 400000, 350000, 450000, 275000, 225000, 375000],
    'sold': [True, False, True, False, True, True, False, True, False, True],
    'city': ['Miami', 'Los Angeles', 'Chicago', 'Houston', 'Houston',
             'San Francisco', 'Chicago', 'Miami', 'Chicago', 'Houston'],
    'house_type': ['Apartment', 'Villa', 'Condo', 'Townhouse', 'Apartment',
                   'Villa', 'Townhouse', 'Condo', 'Apartment', 'Villa'],
    'num_bedrooms': [3, 5, 2, 4, 3, 4, 3, 2, 1, 5],
    'size_sqft': [1200.5, 2500.75, 800.0, 2000.25, 1500.5, 1800.75, 2200.0, 900.0, 1100.5, 2700.0],
    'yard_size': ['medium', 'large', 'small', 'large', 'none', 'small', 'medium', 'none', 'small', 'large']
})

data.head()

In [ ]:
# Exercise 1 which columns should we transform?
# Create a new dataset with the relevant columns transformed with a OneHotEncoder

In [ ]:
# Exercise 2 yard_size is more suitable to be treated as an ordinal category: None=0,small=1,medium=2,large=3 
# HINT: you could use the OrdinalEncoder of sklearn

# Feature scaling
Machine Learning models are very selective about the type and range of values that have to go for their input in order to work well. With the exception of decision trees, most ML models will expect you to scale the input features. What is feature scaling?

Feature scaling is nothing other than transforming the numerical features into a small range of values. In this notebook, we will see the following scaling technique:

- Normalization
- Standardizatiom
- Robust Scaling

## Normalization
Normalization is a scaling techniques that transform the numerical feature to the range of values between 0 and 1. 

Here is a formula that is followed when normalizing the data. $Xmin$ is the minimum value of feature X, and $Xmax$ is the maximum value of X. 

$$
Xnorm = \frac {X-Xmin} {Xmax-Xmin} 
$$

## When Should you Normalize the Features?
When you have features that have different ranges of values, normalizing these features can be a good practice.

Take an example. If you have two features that have different ranges (say one feature from 1-100, other vary from 5-300), you will to scale them so they have the same range of values.

More specifically, normalization is a preferrable scaling technique when the data at hand has not a normal or gaussian distribution. If the data's distribution is gaussian, standardization is a preferrable scaling technique. If you don't know the distribution of the data, still, normalization is a good choice at first.

With that said, when the ML algorithm of choice is either neural network or K-Nearest Neighbors(KNN), normalization is a good choice for these type of algorithms because they don't make any assumption of the input data.

Most popular ML frameworks provide functions to normalize the numerical data. 

For illustration purpose, I will use tips data available in Seaborn.

In [18]:
from seaborn import load_dataset

tip_data = load_dataset('tips')
tip_data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
num_feats = tip_data[['total_bill', 'tip', 'size']]

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

num_scaled = scaler.fit_transform(num_feats)
num_scaled[:5]

array([[0.29157939, 0.00111111, 0.2       ],
       [0.1522832 , 0.07333333, 0.4       ],
       [0.3757855 , 0.27777778, 0.4       ],
       [0.43171345, 0.25666667, 0.2       ],
       [0.45077503, 0.29      , 0.6       ]])

In [20]:
import pandas as pd 

num_scaled_df = pd.DataFrame(num_scaled, columns=num_feats.columns)
num_scaled_df.head()

   total_bill       tip  size
0    0.291579  0.001111   0.2
1    0.152283  0.073333   0.4
2    0.375786  0.277778   0.4
3    0.431713  0.256667   0.2
4    0.450775  0.290000   0.6

## Standardization
In standardization, the numerical features are rescaled to have the 0 mean( u ) and unity standard deviation(std or  σ  ).

Here is the formula of standardization. Xstd is the standardized feature, X is the feature,  u  is mean of the feature, and  σ  is the standard deviation.

$$
Xstd = \frac {X - u} {\sigma}
$$

### When Should you Standardize the Features?

When you know that the training data at hand has a normal or gaussian distribution, you should standardize such data. 

Some ML algorithms such as Support Vector Machines(with rbf kernel) and linear models expect that the input data to have a normal distribution. 

In most cases, whether you choose normalization or standardization, it won't make much difference, but it can. So, it makes sense to try both especially if you are not sure about the distribution of the data.

Here is how Standardization is implemented in Scikit-Learn.

In [ ]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
num_std = std_scaler.fit_transform(num_feats)
num_std[:5]

In [ ]:
# Mean of each feature in the scaled data
std_scaler.mean_

*source: https://github.com/Nyandwi/machine_learning_complete/blob/main/4_real_world_data_analysis_and_preparation/4_feature_scaling.ipynb*

In [ ]:
# Exercise 3 Normalization
# Normalize the numerical columns in below's dataset. 

# Larger Sample Data related to housing prices
sample_data_from_houses = pd.DataFrame({
    'date_sold': ['2023-01-01', '2023-02-15', '2023-03-10', '2023-04-25', '2023-05-30',
                  '2023-06-10', '2023-07-15', '2023-08-20', '2023-09-25', '2023-10-30'],
    'price': [250000, 300000, 150000, 500000, 400000, 350000, 450000, 275000, 225000, 375000],
    'sold': [True, False, True, False, True, True, False, True, False, True],
    'city': ['Miami', 'Los Angeles', 'Chicago', 'Houston', 'Houston',
             'San Francisco', 'Chicago', 'Miami', 'Chicago', 'Houston'],
    'house_type': ['Apartment', 'Villa', 'Condo', 'Townhouse', 'Apartment',
                   'Villa', 'Townhouse', 'Condo', 'Apartment', 'Villa'],
    'num_bedrooms': [3, 5, 2, 4, 3, 4, 3, 2, 1, 5],
    'size_sqft': [1200.5, 2500.75, 800.0, 2000.25, 1500.5, 1800.75, 2200.0, 900.0, 1100.5, 2700.0],
    'yard_size': ['medium', 'large', 'small', 'large', 'none', 'small', 'medium', 'none', 'small', 'large']
})

# ANSWER Exercise 2

In [21]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Larger Sample Data related to housing prices
sample_data_from_houses = pd.DataFrame({
    'date_sold': ['2023-01-01', '2023-02-15', '2023-03-10', '2023-04-25', '2023-05-30',
                  '2023-06-10', '2023-07-15', '2023-08-20', '2023-09-25', '2023-10-30'],
    'price': [250000, 300000, 150000, 500000, 400000, 350000, 450000, 275000, 225000, 375000],
    'sold': [True, False, True, False, True, True, False, True, False, True],
    'city': ['Miami', 'Los Angeles', 'Chicago', 'Houston', 'Houston',
             'San Francisco', 'Chicago', 'Miami', 'Chicago', 'Houston'],
    'house_type': ['Apartment', 'Villa', 'Condo', 'Townhouse', 'Apartment',
                   'Villa', 'Townhouse', 'Condo', 'Apartment', 'Villa'],
    'num_bedrooms': [3, 5, 2, 4, 3, 4, 3, 2, 1, 5],
    'size_sqft': [1200.5, 2500.75, 800.0, 2000.25, 1500.5, 1800.75, 2200.0, 900.0, 1100.5, 2700.0],
    'yard_size': ['medium', 'large', 'small', 'large', 'none', 'small', 'medium', 'none', 'small', 'large']
})

print("Original DataFrame:")
print(sample_data_from_houses.head())

# Ordinal categories for yard_size
yard_size_categories = ['none', 'small', 'medium', 'large']

# Instantiate OrdinalEncoder with defined categories
ordinal_encoder = OrdinalEncoder(categories=[yard_size_categories])

# Apply ordinal encoding to the 'yard_size' column
sample_data_from_houses['yard_size_encoded'] = ordinal_encoder.fit_transform(sample_data_from_houses[['yard_size']])

print("\nDataFrame After Encoding 'yard_size' Column:")
print(sample_data_from_houses.head())

Original DataFrame:
    date_sold   price   sold         city house_type  num_bedrooms  size_sqft  \
0  2023-01-01  250000   True        Miami  Apartment             3    1200.50
1  2023-02-15  300000  False  Los Angeles      Villa             5    2500.75
2  2023-03-10  150000   True      Chicago      Condo             2     800.00
3  2023-04-25  500000  False      Houston  Townhouse             4    2000.25
4  2023-05-30  400000   True      Houston  Apartment             3    1500.50

  yard_size
0    medium
1     large
2     small
3     large
4      none

DataFrame After Encoding 'yard_size' Column:
    date_sold   price   sold         city house_type  num_bedrooms  size_sqft  \
0  2023-01-01  250000   True        Miami  Apartment             3    1200.50
1  2023-02-15  300000  False  Los Angeles      Villa             5    2500.75
2  2023-03-10  150000   True      Chicago      Condo             2     800.00
3  2023-04-25  500000  False      Houston  Townhouse             4    2000.25
4  2023-05-30  400000   True      Houston  Apartment             3    1500.50

  yard_size  yard_size_encoded
0    medium                2.0
1     large                3.0
2     small                1.0
3     large                3.0
4      none                0.0